Repository ripe-tech/ripe-components-react-native, pull requests merged in 2020-04, with the labels that each got.

#130 Icon fill prop on stories
  react/components/atoms/icon/icon.stories.js
Labels: enhancement

#131 #128 Chat: writing scrolls to the end
  react/components/organisms/chat/chat.js
Labels: bug, enhancement

#134 #118: Close keyboard when closing chat.
  react/components/molecules/rich-textinput/rich-textinput.js
  react/components/organisms/chat/chat.js
Labels: bug

#136 #129 Input: app view doesn't shrink on iOS
  react/components/organisms/chat/chat.js
  react/components/organisms/chat/chat.stories.js
Labels: bug, p-low

#140 Creation of Key Value placeholder
  react/components/molecules/index.js
  react/components/molecules/key-value-placeholder/index.js
  react/components/molecules/key-value-placeholder/key-value-placeholder.js
  react/components/molecules/key-value-placeholder/key-value-placeholder.stories.js
Labels: enhancement

#141 Creation of key values placeholder
  react/components/molecules/index.js
  react/components/molecules/key-values-placeholder/index.js
  react/components/molecules/key-values-placeholder/key-values-placeholder.js
  react/components/molecules/key-values-placeholder/key-values-placeholder.stories.js
Labels: enhancement

#144 #149 ButtonIcon component with native feedback
  package.json
  react/components/atoms/button-icon/button-icon.js
  react/components/atoms/button-icon/button-icon.stories.js
Labels: enhancement

#143 #149 Creation of Touchable Component
  package.json
  react/components/atoms/avatar/avatar.js
  react/components/atoms/button-keyboard/button-keyboard.js
  react/components/atoms/button-tab-text/button-tab-text.js
  react/components/atoms/button/button.js
  react/components/atoms/index.js
  react/components/atoms/lightbox/lightbox.js
  react/components/atoms/tag/tag.js
  react/components/atoms/touchable/index.js
  react/components/atoms/touchable/touchable.js
  react/components/atoms/touchable/touchable.stories.js
  react/components/molecules/header/header.js
  react/components/molecules/item-notification/item-notification.js
  react/components/molecules/item/item.js
  react/components/molecules/key-value/key-value.js
  react/components/molecules/keyboard-numeric/keyboard-numeric.js
  react/components/molecules/tabs/tabs.js
  react/components/organisms/image-list/image-list-item-add.js
Labels: enhancement

#146 #155: Device Detection
  react/util/ui-utils.js
Labels: enhancement
