Repository ripe-tech/ripe-components-react-native, pull requests merged in 2021-06, with the labels that each got.

#185 refactor: reorder imports
  react/components/atoms/avatar/avatar.js
  react/components/atoms/badge/badge.js
  react/components/atoms/badge/badge.stories.js
  react/components/atoms/bar-animated/bar-animated.js
  react/components/atoms/button-icon/button-icon.js
  react/components/atoms/button-icon/button-icon.stories.js
  react/components/atoms/button-keyboard/button-keyboard.js
  react/components/atoms/button-keyboard/button-keyboard.stories.js
  react/components/atoms/button-tab-text/button-tab-text.js
  react/components/atoms/button-tab-text/button-tab-text.stories.js
  react/components/atoms/button-tab/button-tab.js
  react/components/atoms/button-tab/button-tab.stories.js
  react/components/atoms/button/button.js
  react/components/atoms/button/button.stories.js
  react/components/atoms/container-draggable/container-draggable.stories.js
  react/components/atoms/container-openable/container-openable.js
  react/components/atoms/container-openable/container-openable.stories.js
  react/components/atoms/container-swipeable/container-swipeable.js
  react/components/atoms/container-swipeable/container-swipeable.stories.js
  react/components/atoms/icon/icon.stories.js
  react/components/atoms/lightbox/lightbox.js
  react/components/atoms/lightbox/lightbox.stories.js
  react/components/atoms/link/link.js
  react/components/atoms/tag/tag.js
  react/components/atoms/tag/tag.stories.js
  react/components/atoms/textarea/textarea.js
  react/components/atoms/textarea/textarea.stories.js
  react/components/atoms/touchable/touchable.js
  react/components/atoms/touchable/touchable.stories.js
  react/components/molecules/chat-message/chat-message.js
  react/components/molecules/chat-message/chat-message.stories.js
  react/components/molecules/header/header.stories.js
  react/components/molecules/item-notification/item-notification.js
  react/components/molecules/item-notification/item-notification.stories.js
  react/components/molecules/item/item.js
  react/components/molecules/item/item.stories.js
  react/components/molecules/key-value-placeholder/key-value-placeholder.js
  react/components/molecules/key-value/key-value.js
  react/components/molecules/key-value/key-value.stories.js
  react/components/molecules/key-values/key-values.js
  react/components/molecules/keyboard-numeric/keyboard-numeric.js
  react/components/molecules/keyboard-numeric/keyboard-numeric.stories.js
  react/components/molecules/rich-textinput/rich-textinput.js
  react/components/molecules/rich-textinput/rich-textinput.stories.js
  react/components/molecules/section-view/section-view.js
  react/components/molecules/tabs-text/tabs-text.js
  react/components/molecules/toast-message/toast-message.js
  react/components/organisms/chat/chat.js
  react/components/organisms/chat/chat.stories.js
  react/components/organisms/image-list/image-list-item-add.js
  react/components/organisms/image-list/image-list-item.js
  react/components/organisms/image-list/image-list.js
Labels: enhancement

#186 refactor: order props to variables -> funcs -> style
  react/components/atoms/lightbox/lightbox.js
  react/components/atoms/textarea/textarea.js
  react/components/atoms/touchable/touchable.js
  react/components/molecules/item-notification/item-notification.js
  react/components/organisms/image-list/image-list-item-add.js
  react/components/organisms/image-list/image-list-item.js
Labels: enhancement

#192 fix: added missing disabled prop and fixed style
  react/components/atoms/button-icon/button-icon.js
  react/components/atoms/button-icon/button-icon.stories.js
Labels: bug

#183 feat: add ios snackbar component
  CHANGELOG.md
  react/components/molecules/index.js
  react/components/molecules/snackbar/index.js
  react/components/molecules/snackbar/snackbar.js
  react/components/molecules/snackbar/snackbar.stories.js
Labels: design, enhancement, p-medium

#190 #317: Toggle button
  CHANGELOG.md
  react/components/atoms/button/button.js
  react/components/molecules/index.js
  react/components/molecules/toggle-button/index.js
  react/components/molecules/toggle-button/toggle-button.js
  react/components/molecules/toggle-button/toggle-button.stories.js
Labels: enhancement

#191 #317: Button group
  react/components/molecules/button-toggle/button-toggle.js
  react/components/molecules/button-toggle/button-toggle.stories.js
  react/components/molecules/button-toggle/index.js
  react/components/molecules/index.js
  react/components/molecules/toggle-button/index.js
  react/components/organisms/button-group/button-group.js
  react/components/organisms/button-group/button-group.stories.js
  react/components/organisms/button-group/index.js
  react/components/organisms/index.js
Labels: enhancement

#184 #317: Date input
  CHANGELOG.md
  package.json
  react/assets/icons/calendar-round.svg
  react/assets/icons/index.js
  react/components/molecules/date-input/date-input.js
  react/components/molecules/date-input/date-input.stories.js
  react/components/molecules/date-input/index.js
  react/components/molecules/index.js
Labels: back-port 🔮, enhancement, p-medium

#193 feat: bump react native image picker enabling multiple image selection
  CHANGELOG.md
  package.json
  react/util/ui-utils.js
Labels: enhancement, p-medium, risky ❕

#175 #317: switcher component
  CHANGELOG.md
  react/components/atoms/index.js
  react/components/atoms/switcher/index.js
  react/components/atoms/switcher/switcher.js
  react/components/atoms/switcher/switcher.stories.js
Labels: back-port 🔮, design, enhancement, p-medium

#187 #317: Progress bar
  CHANGELOG.md
  react/components/atoms/index.js
  react/components/atoms/progress-bar/index.js
  react/components/atoms/progress-bar/progress-bar.js
  react/components/atoms/progress-bar/progress-bar.stories.js
Labels: design, enhancement, p-medium

#179 #317: Radio button component
  CHANGELOG.md
  react/components/atoms/index.js
  react/components/atoms/radio/index.js
  react/components/atoms/radio/radio.js
  react/components/atoms/radio/radio.stories.js
Labels: enhancement, p-medium

#194 fix: normalizeImages function handling of images coming from camera
  CHANGELOG.md
  react/util/ui-utils.js
Labels: enhancement, p-medium, risky ❕

#181 #317: Select component
  CHANGELOG.md
  package.json
  react/components/molecules/index.js
  react/components/molecules/select/index.js
  react/components/molecules/select/select.js
  react/components/molecules/select/select.stories.js
  react/util/utils.js
Labels: back-port 🔮, enhancement
