Repository ripe-tech/ripe-components-react-native, pull requests merged in 2021-04, with the labels that each got.

#164 feat: add scroll behaviour to tabs text
  react/components/molecules/tabs-text/tabs-text.js
Labels: design, enhancement, fast-track

#165 version: 0.3.3
  CHANGELOG.md
  package.json
Labels: enhancement

#167 Text getting cropped in ios
  react/components/atoms/button-tab-text/button-tab-text.js
  react/components/molecules/item/item.js
Labels: bug, fast-track, p-medium

#169 Fix buttonTabText component with 'compact' variant
  react/components/atoms/button-tab-text/button-tab-text.js
Labels: bug, regression

#166 Add selectedTabPressed events to tabs components
  CHANGELOG.md
  react/components/molecules/tabs-text/tabs-text.js
  react/components/molecules/tabs/tabs.js
Labels: enhancement, p-medium, side-quest ✨

#168 Add funtion that picks image from photo gallery to ui-utils
  CHANGELOG.md
  react/assets/icons/index.js
  react/assets/icons/photos.svg
  react/util/ui-utils.js
Labels: enhancement
