Repository ripe-tech/ripe-components-react-native, pull requests merged in 2021-07, with the labels that each got.

#189 #317: Radio-group component
  CHANGELOG.md
  react/components/molecules/index.js
  react/components/molecules/radio-group/index.js
  react/components/molecules/radio-group/radio-group.js
  react/components/molecules/radio-group/radio-group.stories.js
Labels: enhancement

#205 Fix story name format
  react/components/atoms/avatar/avatar.stories.js
  react/components/atoms/badge/badge.stories.js
  react/components/atoms/bar-animated/bar-animated.stories.js
  react/components/atoms/button-icon/button-icon.stories.js
  react/components/atoms/button-keyboard/button-keyboard.stories.js
  react/components/atoms/button-tab-text/button-tab-text.stories.js
  react/components/atoms/button-tab/button-tab.stories.js
  react/components/atoms/button/button.stories.js
  react/components/atoms/checkbox/checkbox.stories.js
  react/components/atoms/container-draggable/container-draggable.stories.js
  react/components/atoms/container-openable/container-openable.stories.js
  react/components/atoms/container-swipeable/container-swipeable.stories.js
  react/components/atoms/fade-view/fade-view.stories.js
  react/components/atoms/icon/icon.stories.js
  react/components/atoms/lightbox/lightbox.stories.js
  react/components/atoms/link/link.stories.js
  react/components/atoms/progress-bar/progress-bar.stories.js
  react/components/atoms/radio/radio.stories.js
  react/components/atoms/switcher/switcher.stories.js
  react/components/atoms/tag/tag.stories.js
  react/components/atoms/text/text.stories.js
  react/components/atoms/textarea/textarea.stories.js
  react/components/atoms/touchable/touchable.stories.js
  react/components/molecules/button-toggle/button-toggle.stories.js
  react/components/molecules/chat-message/chat-message.stories.js
  react/components/molecules/date-input/date-input.stories.js
  react/components/molecules/header/header.stories.js
  react/components/molecules/item-notification/item-notification.stories.js
  react/components/molecules/item/item.stories.js
  react/components/molecules/key-value-placeholder/key-value-placeholder.stories.js
  react/components/molecules/key-value/key-value.stories.js
  react/components/molecules/key-values-placeholder/key-values-placeholder.stories.js
  react/components/molecules/key-values/key-values.stories.js
  react/components/molecules/keyboard-numeric/keyboard-numeric.stories.js
  react/components/molecules/rich-textinput/rich-textinput.stories.js
  react/components/molecules/section-view/section-view.stories.js
  react/components/molecules/select/select.stories.js
  react/components/molecules/snackbar/snackbar.stories.js
  react/components/molecules/tabs-text/tabs-text.stories.js
  react/components/molecules/tabs/tabs.stories.js
  react/components/molecules/toast-message/toast-message.stories.js
  react/components/organisms/button-group/button-group.stories.js
  react/components/organisms/chat/chat.stories.js
  react/components/organisms/image-list/image-list.stories.js
Labels: enhancement

#204 fix: onRichTextInputPhotoAdded function in chat component
  CHANGELOG.md
  react/components/organisms/chat/chat.js
Labels: enhancement

#198 #263 Add onScroll and onScrollBottom props
  CHANGELOG.md
  react/components/organisms/chat/chat.js
Labels: enhancement

#180 feat: add text input component
  CHANGELOG.md
  react/components/atoms/index.js
  react/components/atoms/input/index.js
  react/components/atoms/input/input.js
  react/components/atoms/input/input.stories.js
Labels: design, enhancement, p-medium

#197 #263 Chat scroll animation as optional
  CHANGELOG.md
  react/components/organisms/chat/chat.js
Labels: enhancement

#195 feat: add input-animated component
  CHANGELOG.md
  react/components/molecules/index.js
  react/components/molecules/input-animated/index.js
  react/components/molecules/input-animated/input-animated.js
  react/components/molecules/input-animated/input-animated.stories.js
Labels: design, enhancement, p-medium

#202 feat: port contexts from robin-revamp
  package.json
  react/components/contexts/index.js
  react/components/contexts/oauth-context/index.js
  react/components/contexts/oauth-context/oauth-context.js
  react/components/contexts/onesignal-context/index.js
  react/components/contexts/onesignal-context/onesignal-context.js
  react/components/contexts/placeholder-context/index.js
  react/components/contexts/placeholder-context/placeholder-context.js
  react/components/contexts/pusher-context/index.js
  react/components/contexts/pusher-context/pusher-context.js
  react/components/contexts/ripe-context/index.js
  react/components/contexts/ripe-context/ripe-context.js
  react/components/index.js
  react/components/molecules/item-notification/item-notification.js
Labels: enhancement

#208 feat: do not show key values with no value
  react/components/molecules/key-values/key-values.js
Labels: enhancement

#209 feat: avatar label component
  react/components/atoms/avatar/avatar.js
  react/components/atoms/avatar/avatar.stories.js
Labels: enhancement

#213 feat: avatar image update
  CHANGELOG.md
  react/components/atoms/avatar/avatar.js
Labels: enhancement

#203 Add key value improvement and clipboard util method
  package.json
  react/components/molecules/key-value/key-value.js
  react/util/ui-utils.js
Labels: enhancement

#188 #317: Checkbox-group component
  CHANGELOG.md
  react/components/molecules/checkbox-group/checkbox-group.js
  react/components/molecules/checkbox-group/checkbox-group.stories.js
  react/components/molecules/checkbox-group/index.js
  react/components/molecules/index.js
Labels: design, enhancement, p-medium

#207 feat: tabs button props override and platforme icon
  CHANGELOG.md
  react/assets/icons/extra/platforme.svg
  react/assets/icons/index.js
  react/components/atoms/button-tab/button-tab.js
  react/components/molecules/tabs/tabs.js
Labels: enhancement

#216 feat: add view more button in key values component
  CHANGELOG.md
  react/components/molecules/key-values/key-values.js
  react/components/molecules/key-values/key-values.stories.js
Labels: design, enhancement, p-medium

#210 feat: input form component
  CHANGELOG.md
  react/components/atoms/input/input.js
  react/components/atoms/textarea/textarea.js
  react/components/molecules/index.js
  react/components/molecules/input-form/index.js
  react/components/molecules/input-form/input-form.js
  react/components/molecules/input-form/input-form.stories.js
Labels: enhancement

#215 Feat: Knob and overlay opacity configuration
  CHANGELOG.md
  react/components/atoms/container-openable/container-openable.js
Labels: enhancement

#200 Feat: Different borders between key-value pairs by prop
  CHANGELOG.md
  react/components/molecules/key-value-placeholder/key-value-placeholder.js
  react/components/molecules/key-value-placeholder/key-value-placeholder.stories.js
  react/components/molecules/key-value/key-value.js
  react/components/molecules/key-value/key-value.stories.js
  react/components/molecules/key-values-placeholder/key-values-placeholder.js
  react/components/molecules/key-values-placeholder/key-values-placeholder.stories.js
  react/components/molecules/key-values/key-values.js
  react/components/molecules/key-values/key-values.stories.js
Labels: enhancement

#220 fix: make text and opacity container smaller
  react/components/atoms/avatar/avatar.js
Labels: bug

#222 Icon: Add icon sources through URI or local require
  react/components/atoms/icon/icon.js
Labels: enhancement

#219 Key values: prop to allow copy to clipboard on long press
  react/components/molecules/key-value/key-value.js
  react/components/molecules/key-values/key-values.js
Labels: enhancement

#218 Select: Add border radius variant
  react/components/molecules/select/select.js
  react/components/molecules/select/select.stories.js
Labels: enhancement

#223 #266 Select: color props
  react/components/molecules/select/select.js
  react/components/molecules/select/select.stories.js
Labels: enhancement

#214 #5 Search
  react/components/molecules/index.js
  react/components/molecules/search/index.js
  react/components/molecules/search/search.js
  react/components/molecules/search/search.stories.js
Labels: enhancement

#211 feat: form component
  CHANGELOG.md
  react/components/molecules/date-input/date-input.js
  react/components/molecules/date-input/date-input.stories.js
  react/components/molecules/key-values/key-values.js
  react/components/organisms/form/form.js
  react/components/organisms/form/form.stories.js
  react/components/organisms/form/index.js
  react/components/organisms/index.js
Labels: enhancement

#227 Icon: Add svg icon option
  CHANGELOG.md
  react/components/atoms/icon/icon.js
Labels: enhancement

#228 Fix: Link.url is not required
  react/components/atoms/link/link.js
Labels: bug

#229 feat: move logic to ripe-commons-native
  package.json
  react/components/atoms/avatar/avatar.js
  react/components/atoms/button-keyboard/button-keyboard.js
  react/components/atoms/button-tab-text/button-tab-text.js
  react/components/atoms/checkbox/checkbox.js
  react/components/atoms/lightbox/lightbox.js
  react/components/atoms/radio/radio.js
  react/components/atoms/tag/tag.js
  react/components/atoms/textarea/textarea.js
  react/components/contexts/index.js
  react/components/contexts/oauth-context/index.js
  react/components/contexts/oauth-context/oauth-context.js
  react/components/contexts/onesignal-context/index.js
  react/components/contexts/onesignal-context/onesignal-context.js
  react/components/contexts/placeholder-context/index.js
  react/components/contexts/placeholder-context/placeholder-context.js
  react/components/contexts/pusher-context/index.js
  react/components/contexts/pusher-context/pusher-context.js
  react/components/contexts/ripe-context/index.js
  react/components/contexts/ripe-context/ripe-context.js
  react/components/index.js
  react/components/molecules/chat-message/chat-message.js
  react/components/molecules/item-notification/item-notification.js
  react/components/molecules/item/item.js
  react/components/molecules/key-value/key-value.js
  react/components/molecules/key-values/key-values.js
  react/components/molecules/keyboard-numeric/keyboard-numeric.js
  react/components/molecules/rich-textinput/rich-textinput.js
  react/components/molecules/select/select.js
  react/components/molecules/tabs-text/tabs-text.js
  react/components/organisms/image-list/image-list.js
  react/util/index.js
  react/util/mixins/identifiable.js
  react/util/mixins/index.js
  react/util/ui-utils.js
  react/util/utils.js
Labels: enhancement

#225 Feat: Enable container openable overlay press by prop
  react/components/atoms/container-openable/container-openable.js
Labels: enhancement

#224 feat: button group variant "flat" and vertical orientation
  react/components/atoms/button/button.js
  react/components/atoms/button/button.stories.js
  react/components/molecules/button-toggle/button-toggle.js
  react/components/molecules/button-toggle/button-toggle.stories.js
  react/components/organisms/button-group/button-group.js
  react/components/organisms/button-group/button-group.stories.js
Labels: enhancement

#231 fix: use icon with stroke width similar to all other icons
  react/assets/icons/calendar-round.svg
  react/components/molecules/date-input/date-input.js
Labels: bug

#230 fix: input animated keyboard avoiding view problem fix
  react/components/molecules/input-animated/input-animated.js
Labels: bug

#212 #5 Card, item, search
  react/components/atoms/icon/icon.js
  react/components/molecules/card/card.js
  react/components/molecules/card/card.stories.js
  react/components/molecules/card/index.js
  react/components/molecules/index.js
  react/components/molecules/item/item.js
  react/components/molecules/search/index.js
  react/components/molecules/search/search.js
  react/components/molecules/search/search.stories.js
Labels: enhancement

#226 Header: Add missing prop for style override
  react/components/molecules/header/header.js
Labels: enhancement

#239 Card: Improve spacing
  react/components/molecules/card/card.js
Labels: enhancement

#240 feat: button tab fill prop and fix platformE icon
  react/assets/icons/extra/platforme.svg
  react/components/atoms/button-tab/button-tab.js
  react/components/molecules/tabs/tabs.js
Labels: enhancement

#236 feat: override button toggle style
  react/components/molecules/button-toggle/button-toggle.js
  react/components/organisms/button-group/button-group.js
Labels: enhancement

#238 feat: add padding section on form
  react/components/organisms/form/form.js
Labels: enhancement

#237 Feat: Add onSubmitEditing prop to Input and InputAnimated
  react/components/atoms/input/input.js
  react/components/molecules/input-animated/input-animated.js
Labels: enhancement

#201 #199: Image carrousel component
  CHANGELOG.md
  react/components/molecules/image-carrousel/image-carrousel.js
  react/components/molecules/image-carrousel/image-carrousel.stories.js
  react/components/molecules/image-carrousel/index.js
  react/components/molecules/index.js
Labels: enhancement, p-medium

#234 Button: fix util undefined import
  react/components/atoms/button/button.js
  react/components/molecules/button-toggle/button-toggle.js
  react/components/molecules/card/card.js
Labels: bug

#235 Select: Adapt padding
  CHANGELOG.md
  react/components/molecules/select/select.js
Labels: enhancement

#241 Bump versions: upgrade ripe-commons-native to 0.2.0
  package.json
Labels: enhancement

#243 fix: tabs proptypes
  react/components/molecules/tabs/tabs.js
Labels: bug

#242 fix: make date input spacing similar to input form and prop rename
  react/components/molecules/date-input/date-input.js
Labels: bug

#232 fix: keyboard avoiding view fix for ios with multiline input
  react/components/atoms/textarea/textarea.js
  react/components/organisms/form/form.js
Labels: bug

#244 #5 Listing getitems
  package.json
  react/assets/icons/calendar-round.svg
  react/components/organisms/listing/listing.js
Labels: enhancement

#245 version: 0.5.1
  CHANGELOG.md
  package.json
Labels: enhancement

#246 Listing: small improvements
  react/components/organisms/listing/listing.js
Labels: enhancement

#249 Select: Add right padding to select
  CHANGELOG.md
  react/components/molecules/select/select.js
Labels: enhancement

#251 Profile component
  CHANGELOG.md
  react/components/organisms/index.js
  react/components/organisms/profile/index.js
  react/components/organisms/profile/profile.js
  react/components/organisms/profile/profile.stories.js
Labels: enhancement

#253 Select: fix touchable area
  CHANGELOG.md
  react/components/molecules/select/select.js
Labels: bug

#254 Listing: set of improvements
  CHANGELOG.md
  react/components/organisms/listing/listing.js
Labels: enhancement

#256 feat: avoid scroll chat when opening 1st time
  CHANGELOG.md
  react/components/organisms/chat/chat.js
Labels: enhancement

#255 feat: use linear animation in container openable component
  react/components/atoms/container-openable/container-openable.js
Labels: enhancement, high-value 💰, p-high

#250 Listing: select filter smart fill
  CHANGELOG.md
  react/components/organisms/listing/listing.js
Labels: enhancement

#257 version: 0.6.0
  CHANGELOG.md
  package.json
Labels: enhancement

#258 feat: add no messages ion to chat
  CHANGELOG.md
  react/components/organisms/chat/assets/no-messages.png
  react/components/organisms/chat/chat.js
Labels: enhancement
