Repository ripe-tech/ripe-components-react-native, pull requests merged in 2021-05, with the labels that each got.

#170 fix: better looking TextArea component in ios
  CHANGELOG.md
  react/components/atoms/textarea/textarea.js
Labels: enhancement

#172 fix: remove dead code
  .travis.yml
  package.json
  react/components/organisms/chat/chat.stories.js
  react/components/organisms/image-list/image-list.stories.js
  react/util/ui-utils.js
Labels: enhancement

#173 feat: request camera permissions on pickImage
  react/util/ui-utils.js
Labels: enhancement

#174 feat: backport avatar component functionality from vue version
  CHANGELOG.md
  react/components/atoms/avatar/assets/avatar.png
  react/components/atoms/avatar/avatar.js
Labels: enhancement

#176 fix: onError event handling
  react/components/atoms/avatar/avatar.js
Labels: bug

#177 fix: storybook number knobs undefined default values error
  react/components/atoms/avatar/avatar.stories.js
  react/components/atoms/button/button.stories.js
  react/components/atoms/lightbox/lightbox.stories.js
  react/components/atoms/textarea/textarea.stories.js
  react/components/molecules/item/item.stories.js
  react/components/molecules/rich-textinput/rich-textinput.stories.js
Labels: bug, fast-track

#178 #317: Checkbox component
  CHANGELOG.md
  react/assets/icons/check-blue.svg
  react/assets/icons/check-gray.svg
  react/assets/icons/check.svg
  react/assets/icons/index.js
  react/assets/icons/minus-round-blue.svg
  react/assets/icons/minus-round-gray.svg
  react/assets/icons/minus-round.svg
  react/components/atoms/checkbox/checkbox.js
  react/components/atoms/checkbox/checkbox.stories.js
  react/components/atoms/checkbox/index.js
  react/components/atoms/index.js
  react/components/atoms/touchable/touchable.js
Labels: enhancement
