Repository ripe-tech/ripe-components-react-native, pull requests merged in 2021-02, with the labels that each got.

#155 feat: file fallback name
  .gitignore
  react/util/ui-utils.js
  react/util/utils.js
Labels: enhancement

#156 fix: add buffer peer dependency
  package.json
Labels: enhancement

#157 Gc/basename
  .github/workflows/deploy.yml
  .travis.yml
  package.json
Labels: enhancement

#158 #28 Remove workflow for node 11
  .github/workflows/main.yml
  .travis.yml
Labels: bug

#159 Fix storybook component search
  react/components/atoms/avatar/avatar.stories.js
  react/components/atoms/badge/badge.stories.js
  react/components/atoms/bar-animated/bar-animated.stories.js
  react/components/atoms/button-icon/button-icon.stories.js
  react/components/atoms/button-keyboard/button-keyboard.stories.js
  react/components/atoms/button-tab-text/button-tab-text.stories.js
  react/components/atoms/button-tab/button-tab.stories.js
  react/components/atoms/button/button.stories.js
  react/components/atoms/container-draggable/container-draggable.stories.js
  react/components/atoms/container-openable/container-openable.stories.js
  react/components/atoms/container-swipeable/container-swipeable.stories.js
  react/components/atoms/fade-view/fade-view.stories.js
  react/components/atoms/icon/icon.stories.js
  react/components/atoms/lightbox/lightbox.stories.js
  react/components/atoms/link/link.stories.js
  react/components/atoms/tag/tag.stories.js
  react/components/atoms/text/text.stories.js
  react/components/atoms/textarea/textarea.stories.js
  react/components/atoms/touchable/touchable.stories.js
  react/components/molecules/chat-message/chat-message.stories.js
  react/components/molecules/header/header.stories.js
  react/components/molecules/item-notification/item-notification.stories.js
  react/components/molecules/item/item.stories.js
  react/components/molecules/key-value-placeholder/key-value-placeholder.stories.js
  react/components/molecules/key-value/key-value.stories.js
  react/components/molecules/key-values-placeholder/key-values-placeholder.stories.js
  react/components/molecules/key-values/key-values.stories.js
  react/components/molecules/keyboard-numeric/keyboard-numeric.stories.js
  react/components/molecules/rich-textinput/rich-textinput.stories.js
  react/components/molecules/section-view/section-view.stories.js
  react/components/molecules/tabs-text/tabs-text.stories.js
  react/components/molecules/tabs/tabs.stories.js
  react/components/molecules/toast-message/toast-message.stories.js
  react/components/organisms/chat/chat.stories.js
  react/components/organisms/image-list/image-list.stories.js
Labels: back-port 🔮, bug, enhancement

#160 feat: compatible with react-native 0.63
  package.json
  react/components/atoms/container-openable/container-openable.js
  react/components/atoms/container-swipeable/container-swipeable.js
  react/components/atoms/fade-view/fade-view.js
  react/components/atoms/link/link.js
  react/components/molecules/rich-textinput/rich-textinput.js
  react/components/organisms/image-list/image-list.js
  react/util/ui-utils.js
Labels: enhancement

#161 feat: improve camera error message
  react/util/ui-utils.js
Labels: enhancement

#162 fix: document picking on iOS with spaces
  react/util/ui-utils.js
Labels: enhancement
