Repository ripe-tech/ripe-components-react-native, pull requests merged in 2022-09, with the labels that each got.

#346 #377 Label prop override
  CHANGELOG.md
  react/components/atoms/status-entry/status-entry.js
  react/components/molecules/chat-message/chat-message.js
  react/components/molecules/key-values/key-values.js
  react/components/organisms/chat/assets/no-messages-animation.svg
  react/components/organisms/chat/chat.js
  react/components/organisms/image-list/image-list.js
  react/components/organisms/listing/listing.js
  react/components/organisms/profile/profile.js
Labels: enhancement

#347 feat: using different border color when search input is focused
  CHANGELOG.md
  react/components/molecules/search/search.js
Labels: enhancement

#349 Replace subscription icons
  CHANGELOG.md
  react/assets/icons/mute.svg
  react/assets/icons/volume-loud.svg
Labels: enhancement

#350 fix: no messages animation
  CHANGELOG.md
  react/components/organisms/chat/assets/no-messages-animation.svg
  react/components/organisms/chat/assets/no-messages-animation.svga
  react/components/organisms/chat/chat.js
Labels: enhancement

#351 version: 0.27.3 :rainbow:
  CHANGELOG.md
  package.json
Labels: release 🎉

#352 fix: include svga files
  CHANGELOG.md
  package.json
Labels: bug

#355 fix: add guard to flatlist reference
  react/components/organisms/listing/listing.js
Labels: enhancement

#356 version: 0.27.5 :rainbow:
  CHANGELOG.md
  package.json
Labels: release 🎉

#357 Change default loading indicator color to gray
  react/components/atoms/button-icon/button-icon.js
  react/components/organisms/listing/listing.js
Labels: enhancement, no-changelog

#358 version: 0.27.6
  CHANGELOG.md
  package.json
Labels: release 🎉

#360 Changed the position of the loading indicator for listing
  CHANGELOG.md
  react/components/organisms/listing/listing.js
Labels: enhancement

#359 feat: Add sections to `key-values` components
  CHANGELOG.md
  react/components/molecules/key-values/key-values.js
  react/components/molecules/key-values/key-values.stories.js
Labels: enhancement, p-medium
