Repository ripe-tech/ripe-components-react-native, pull requests merged in 2022-03, with the labels that each got.

#305 #337: Component that shows placeholder while image is loading - `ImageLoading`
  CHANGELOG.md
  react/components/atoms/image-loading/image-loading.js
  react/components/atoms/image-loading/image-loading.stories.js
  react/components/atoms/image-loading/index.js
  react/components/atoms/index.js
  react/components/atoms/lightbox/lightbox.js
  react/components/molecules/chat-message/chat-message.js
  react/components/organisms/chat/chat.js
Labels: enhancement

#306 version: 0.20.0
  CHANGELOG.md
  package.json
Labels: enhancement, release 🎉

#308 #347: Tweak avatar positioning in chat message to match new design
  CHANGELOG.md
  react/components/atoms/lightbox/lightbox.js
  react/components/molecules/chat-message/chat-message.js
Labels: enhancement

#310 #345: `StatusEntry` component and its usage in `ChatMessage` and `Chat`
  CHANGELOG.md
  react/components/atoms/attachment/attachment.js
  react/components/atoms/attachment/attachments.stories.js
  react/components/atoms/index.js
  react/components/atoms/status-entry/index.js
  react/components/atoms/status-entry/status-entry.js
  react/components/atoms/status-entry/status-entry.stories.js
  react/components/molecules/chat-message/chat-message.js
  react/components/molecules/chat-message/chat-message.stories.js
  react/components/organisms/chat/chat.js
  react/components/organisms/chat/chat.stories.js
Labels: enhancement

#311 #347: `AvatarList` component
  CHANGELOG.md
  react/components/molecules/avatar-list/avatar-list.js
  react/components/molecules/avatar-list/avatar-list.stories.js
  react/components/molecules/avatar-list/index.js
  react/components/molecules/chat-message/chat-message.js
  react/components/molecules/chat-message/chat-message.stories.js
  react/components/molecules/index.js
  react/components/organisms/chat/chat.js
  react/components/organisms/chat/chat.stories.js
Labels: enhancement

#312 #343 Set of small fixes
  CHANGELOG.md
  react/components/atoms/button-icon/button-icon.js
  react/components/atoms/button-icon/button-icon.stories.js
  react/components/atoms/button-tab-text/button-tab-text.js
  react/components/atoms/image-loading/image-loading.js
  react/components/molecules/avatar-list/avatar-list.stories.js
  react/components/molecules/item/item.js
  react/components/molecules/item/item.stories.js
  react/components/molecules/select/select.js
  react/components/molecules/tabs-text/tabs-text.js
  react/components/organisms/listing/listing.js
Labels: bug, enhancement
