Repository ripe-tech/ripe-components-react-native, pull requests merged in 2022-04, with the labels that each got.

#315 #316: Tag does not allow text breaking
  CHANGELOG.md
  react/components/atoms/tag/tag.js
Labels: enhancement

#314 #346 Chat
  CHANGELOG.md
  react/assets/icons/extra/chat-balloons.svg
  react/components/molecules/avatar-list/avatar-list.js
  react/components/molecules/chat-message/chat-message.js
  react/components/molecules/tabs/tabs.js
  react/components/organisms/chat/chat.js
Labels: enhancement

#313 feat: more style props for listing
  CHANGELOG.md
  react/components/molecules/search/search.js
  react/components/molecules/select/select.js
  react/components/molecules/select/select.stories.js
  react/components/organisms/listing/listing.js
  react/components/organisms/listing/listing.stories.js
Labels: enhancement

#317 version: 0.21.0
  CHANGELOG.md
  package.json
Labels: release 🎉

#318 #346 Chat: Add `renderBeforeMessages` prop
  CHANGELOG.md
  react/components/organisms/chat/chat.js
Labels: enhancement

#316 Tabs: Visibility toggling via tab options
  CHANGELOG.md
  react/components/molecules/tabs/tabs.js
Labels: enhancement

#320 feat: round touch feedback for header buttons in Android
  CHANGELOG.md
  react/components/molecules/header/header.js
Labels: enhancement

#323 feat: allow gesture movements on the whole container of `ContainerOpenable`
  CHANGELOG.md
  react/components/atoms/container-draggable/container-draggable.js
  react/components/atoms/container-openable/container-openable.js
Labels: enhancement

#325 feat: pan on whole content of ContainerOpenable
  CHANGELOG.md
  react/components/atoms/container-draggable/container-draggable.js
Labels: enhancement

#326 version: 0.23.0
  CHANGELOG.md
  package.json
Labels: fast-track, release 🎉
