Repository ripe-tech/ripe-components-react-native, pull requests merged in 2022-02, with the labels that each got.

#290 #286: Support for modal-like image viewing and zooming
  CHANGELOG.md
  package.json
  react/components/atoms/lightbox/lightbox.js
Labels: enhancement, fast-track, feature-request 💡

#292 fix: Lightbox image style prop
  CHANGELOG.md
  react/components/atoms/lightbox/lightbox.js
Labels: enhancement, fast-track

#293 fix: remove margin top for some key values in profile
  CHANGELOG.md
  react/components/organisms/profile/profile.js
Labels: bug

#295 feat: added `source` prop to lightbox
  CHANGELOG.md
  react/components/atoms/lightbox/lightbox.js
Labels: enhancement

#294 #315: New design for tabs text
  CHANGELOG.md
  react/components/atoms/button-tab-text/button-tab-text.js
  react/components/atoms/button-tab-text/button-tab-text.stories.js
  react/components/molecules/item/item.js
  react/components/molecules/tabs-text/tabs-text.js
  react/components/molecules/tabs-text/tabs-text.stories.js
Labels: enhancement

#296 version: 0.16.0
  CHANGELOG.md
  package.json
Labels: enhancement, release 🎉

#297 feat: bump dependencies and made required changes
  .github/workflows/deploy.yml
  .github/workflows/main.yml
  CHANGELOG.md
  package.json
  react/components/atoms/lightbox/lightbox.js
  react/components/atoms/lightbox/lightbox.stories.js
Labels: enhancement, blocked ⛔

#298 fix: remove node 15 from github workflow
  .github/workflows/main.yml
Labels: bug

#299 version: 0.18.0
  CHANGELOG.md
  package.json
Labels: enhancement, release 🎉

#303 fix: set of fixes in several components
  CHANGELOG.md
  react/components/molecules/chat-message/chat-message.js
  react/components/molecules/item/item.js
  react/components/molecules/key-values/key-values.js
Labels: bug

#300 fix: use index of current route to choose the selected tab in `Tabs`
  CHANGELOG.md
  react/components/molecules/tabs/tabs.js
Labels: bug

#302 feat: unify profile component and allow action for key values
  CHANGELOG.md
  react/components/organisms/profile/profile.js
Labels: enhancement
